# Generated by Django 5.2.1 on 2025-06-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='public_date',
        ),
    ]
